#!/bin/bash
set -e

# Install Quarto
QUARTO_VERSION=1.4.537
curl -o quarto-linux-amd64.deb -L https://github.com/quarto-dev/quarto-cli/releases/download/v${QUARTO_VERSION}/quarto-${QUARTO_VERSION}-linux-amd64.deb
dpkg -i quarto-linux-amd64.deb
rm quarto-linux-amd64.deb

# Install TinyTeX for PDF rendering
quarto install tinytex
